name: Release

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup pnpm
        uses: pnpm/action-setup@v2

      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          cache: pnpm
          node-version: 16
          registry-url: https://registry.npmjs.org

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build:ci

      - name: Lint
        run: pnpm lint

      - name: Test
        run: pnpm test

      - name: Release
        id: release
        if: github.event_name == 'push'
        uses: GoogleCloudPlatform/release-please-action@v2
        with:
          release-type: node
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true

      - name: Publish
        if: ${{ steps.release.outputs.release_created }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm publish
